### ISSUE TITLE
Как передать attrs?

### ISSUE THREAD

**Issue by alpacas9** [mounlion/telegraph-node#8]
Привет, спасибо за либу, за проделанную работу! :)
Подскажите, каким образом можно передать "attrs"? т.е. как передавать теги, такие как anchor или img с соответствующими атрибутами и значениями - href, src и т.д? Буду благодарен за помощь :)

**Comment by alpacas9** [comment]
Если не затруднит, напишите пример. Спасибо

**Comment by fonov** [comment]
Привет

ph.createPage(token, 'Fonov Sergei', [{tag: 'a', attrs: {href: 'ya.ru'}, children: ['Hello world!']}], {
    return_content: true
}).then((result) => {
 console.log(result)
})

Напомню что либа по оф апи http://telegra.ph/api.
Данный пример я составил ссылаясь на нее

**Comment by alpacas9** [comment]
Спасибо!

**Comment by greatspoke** [comment]
Добрый день

Хочу сделать так
```
ph.editPage(token2, 'sale-shop-bot-09-04-6', 'sale_shop_bot',


    [

   {tag: 'img', attrs: {src: 'https://m.media-amazon.com/images/I/71nLg4V7pJL._AC_SX255_.jpg'}},

        {tag: 'a', attrs: {href: 'https://www.6pm.com/p/calvin-klein-georgeanna-black-stretch-micro-suede/product/8985491/color/727099'}, children: ['Georgeanna 💵 $68.70 ']},


        {tag: 'img', attrs: {src: 'https://m.media-amazon.com/images/I/71nLg4V7pJL._AC_SX255_.jpg'}},

        {tag: 'a', attrs: {href: 'https://www.6pm.com/p/calvin-klein-georgeanna-black-stretch-micro-suede/product/8985491/color/727099'}, children: ['Georgeanna 💵 $68.70 ']},

    ], {
    return_content: true
}).then((result) => {
    console.log(result)
})
```

Не выходит получается все в перемешку не подскажите пожалуйста как делать подряд картинку и текст? Спасибо заранее!

**Comment by fonov** [comment]
Добрый день
Репозиторий к сожалению больше не поддерживается

**Comment by greatspoke** [comment]
Спасибо но все же было бы неплохо подсказать вообще такое возможно сделать.?
